### ISSUE TITLE
Permitir creación de productos sin proveedor especificado

### ISSUE THREAD

**Issue by Thayrov** [MercadilloCivico/MercadilloCivico#370]
Actualmente, el sistema no permite crear productos sin asignar un proveedor. Esta limitación debe ser revisada y corregida.

**Comment by ArphaxadCR** [comment]
Sí se puede crear un producto sin proveedores, en punto de venta al momento de querer asociar un inventario con un producto (que es en donde está afectando esto principalmente) se deberían renderizar sólo los productos que sí cuentan con proveedores, y los productos que no tienen proveedores que el admin los edite y les agregue proveedores
